#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 02:59:09 PM 17 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=	-L../../clibrary

incDirs	=	-I../../clibrary

LD_FLAGS =	-s
LIBS	=	-lgflib -lm
C_FLAGS	=	-O

SRCS	=\
	sidtime.c

EXOBJS	=\
	$(oDir)/sidtime.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libsidtime.a
ALLTGT	=	$(Bin)/libsidtime.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libsidtime.a: $(EXOBJS)
	rm -f $(Bin)/libsidtime.a
	ar cr $(Bin)/libsidtime.a $(EXOBJS)
	ranlib $(Bin)/libsidtime.a

$(oDir)/sidtime.o: sidtime.c ../../clibrary/gflib.h sidtime.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
