#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 04:07:56 PM 06 Feb 2011
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=	-L../../clibrary

incDirs	=	-I../../clibrary

LD_FLAGS =	-s
LIBS	=	-lgflib -lm
C_FLAGS	=	-O

SRCS	=\
	gftermio.c

EXOBJS	=\
	$(oDir)/gftermio.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libgftermio.a
ALLTGT	=	$(Bin)/libgftermio.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libgftermio.a: $(EXOBJS)
	rm -f $(Bin)/libgftermio.a
	ar cr $(Bin)/libgftermio.a $(EXOBJS)
	ranlib $(Bin)/libgftermio.a

$(oDir)/gftermio.o: gftermio.c ../../clibrary/gflib.h gftermio.h os/gftiolin.c
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
