#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 03:26:25 PM 17 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=
incDirs	=
LD_FLAGS =	-s
LIBS	=	-lm
C_FLAGS	=	-O

SRCS	=\
	bgdash.c\
	gylog.c\
	bginit.c\
	bgshow.c\
	bgstart.c\
	cg_newfuncs.c\
	cgprint.c\
	cgsave.c\
	gaxlabel.c\
	gbott.c\
	gcord.c\
	gfont.c\
	ggraycolor.c\
	glcmp.c\
	gmark.c\
	gmesh.c\
	gmlin.c\
	gorig.c\
	gprim.c\
	grmle.c\
	grset.c\
	gstrk.c\
	gstyl.c\
	gtext.c\
	gtrnc.c\
	gwdth.c\
	gxaxs.c\
	gxlog.c\
	gyaxs.c

EXOBJS	=\
	$(oDir)/bgdash.o\
	$(oDir)/gylog.o\
	$(oDir)/bginit.o\
	$(oDir)/bgshow.o\
	$(oDir)/bgstart.o\
	$(oDir)/cg_newfuncs.o\
	$(oDir)/cgprint.o\
	$(oDir)/cgsave.o\
	$(oDir)/gaxlabel.o\
	$(oDir)/gbott.o\
	$(oDir)/gcord.o\
	$(oDir)/gfont.o\
	$(oDir)/ggraycolor.o\
	$(oDir)/glcmp.o\
	$(oDir)/gmark.o\
	$(oDir)/gmesh.o\
	$(oDir)/gmlin.o\
	$(oDir)/gorig.o\
	$(oDir)/gprim.o\
	$(oDir)/grmle.o\
	$(oDir)/grset.o\
	$(oDir)/gstrk.o\
	$(oDir)/gstyl.o\
	$(oDir)/gtext.o\
	$(oDir)/gtrnc.o\
	$(oDir)/gwdth.o\
	$(oDir)/gxaxs.o\
	$(oDir)/gxlog.o\
	$(oDir)/gyaxs.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libcgraphps.a
ALLTGT	=	$(Bin)/libcgraphps.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libcgraphps.a: $(EXOBJS)
	rm -f $(Bin)/libcgraphps.a
	ar cr $(Bin)/libcgraphps.a $(EXOBJS)
	ranlib $(Bin)/libcgraphps.a

$(oDir)/bgdash.o: bgdash.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gylog.o: gylog.c cglobals.h cgaxes.h cgfont.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/bginit.o: bginit.c version.h cglobals.h cgfont.h cgaxes.h cgraph.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/bgshow.o: bgshow.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/bgstart.o: bgstart.c cglobals.h cgaxes.h cgfont.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/cg_newfuncs.o: cg_newfuncs.c cglobals.h cgfont.h cgaxes.h cgraph.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/cgprint.o: cgprint.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/cgsave.o: cgsave.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gaxlabel.o: gaxlabel.c cglobals.h cgaxes.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gbott.o: gbott.c cglobals.h cgaxes.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gcord.o: gcord.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gfont.o: gfont.c cglobals.h cgfont.h PS_font_names.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/ggraycolor.o: ggraycolor.c cglobals.h cgraph.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/glcmp.o: glcmp.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gmark.o: gmark.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gmesh.o: gmesh.c cglobals.h cgaxes.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gmlin.o: gmlin.c cgraph.h cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gorig.o: gorig.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gprim.o: gprim.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/grmle.o: grmle.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/grset.o: grset.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gstrk.o: gstrk.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gstyl.o: gstyl.c cgaxes.h cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gtext.o: gtext.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gtrnc.o: gtrnc.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gwdth.o: gwdth.c cglobals.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gxaxs.o: gxaxs.c cglobals.h cgaxes.h cgfont.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gxlog.o: gxlog.c cglobals.h cgaxes.h cgfont.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gyaxs.o: gyaxs.c cglobals.h cgfont.h cgaxes.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
