#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 03:22:21 PM 17 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=
incDirs	=
LD_FLAGS =	-s
LIBS	=	-lm
C_FLAGS	=	-O

SRCS	=\
	sqlite3.c

EXOBJS	=\
	$(oDir)/sqlite3.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libsqlite3.a
ALLTGT	=	$(Bin)/libsqlite3.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libsqlite3.a: $(EXOBJS)
	rm -f $(Bin)/libsqlite3.a
	ar cr $(Bin)/libsqlite3.a $(EXOBJS)
	ranlib $(Bin)/libsqlite3.a

$(oDir)/sqlite3.o: sqlite3.c
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
