#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 06:42:14 PM 18 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=	-L../../clibrary

incDirs	=	-I../../clibrary

LD_FLAGS =	-s
LIBS	=	-lgflib -llconio -lm
C_FLAGS	=	-O

SRCS	=\
	lconio.c

EXOBJS	=\
	$(oDir)/lconio.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/liblconio.a
ALLTGT	=	$(Bin)/liblconio.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/liblconio.a: $(EXOBJS)
	rm -f $(Bin)/liblconio.a
	ar cr $(Bin)/liblconio.a $(EXOBJS)
	ranlib $(Bin)/liblconio.a

$(oDir)/lconio.o: lconio.c lconio.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
