#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 03:20:02 PM 17 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=
incDirs	=
LD_FLAGS =	-s
LIBS	=	-lm
C_FLAGS	=	-O

SRCS	=\
	shputils.c\
	dbfcreate.c\
	dbfdump.c\
	dbfopen.c\
	shpadd.c\
	shpcreate.c\
	shpdump.c\
	shpopen.c\
	shprewind.c\
	shptest.c\
	shptree.c\
	shptreedump.c\
	dbfadd.c

EXOBJS	=\
	$(oDir)/shputils.o\
	$(oDir)/dbfcreate.o\
	$(oDir)/dbfdump.o\
	$(oDir)/dbfopen.o\
	$(oDir)/shpadd.o\
	$(oDir)/shpcreate.o\
	$(oDir)/shpdump.o\
	$(oDir)/shpopen.o\
	$(oDir)/shprewind.o\
	$(oDir)/shptest.o\
	$(oDir)/shptree.o\
	$(oDir)/shptreedump.o\
	$(oDir)/dbfadd.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libshapelib.a
ALLTGT	=	$(Bin)/libshapelib.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libshapelib.a: $(EXOBJS)
	rm -f $(Bin)/libshapelib.a
	ar cr $(Bin)/libshapelib.a $(EXOBJS)
	ranlib $(Bin)/libshapelib.a

$(oDir)/shputils.o: shputils.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/dbfcreate.o: dbfcreate.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/dbfdump.o: dbfdump.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/dbfopen.o: dbfopen.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shpadd.o: shpadd.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shpcreate.o: shpcreate.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shpdump.o: shpdump.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shpopen.o: shpopen.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shprewind.o: shprewind.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shptest.o: shptest.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shptree.o: shptree.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/shptreedump.o: shptreedump.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/dbfadd.o: dbfadd.c shapefil.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
