#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 03:24:04 PM 17 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=
incDirs	=
LD_FLAGS =	-s
LIBS	=	-lm
C_FLAGS	=	-O

SRCS	=\
	cprt.c\
	swrite.c\
	error.c\
	fopenv.c\
	outofmem.c\
	rdcolor.c\
	saccept.c\
	sclose.c\
	sgets.c\
	sinit.c\
	smaskwait.c\
	smkskt.c\
	sopen.c\
	sopenv.c\
	speek.c\
	speeraddr.c\
	speername.c\
	sprintf.c\
	sprt.c\
	sprtskt.c\
	sputs.c\
	sread.c\
	sreadbytes.c\
	srmsrvr.c\
	srmtrblk.c\
	sscanf.c\
	stest.c\
	stimeoutwait.c\
	stpblk.c\
	stpnxt.c\
	strnxtfmt.c\
	svprintf.c\
	swait.c

EXOBJS	=\
	$(oDir)/cprt.o\
	$(oDir)/swrite.o\
	$(oDir)/error.o\
	$(oDir)/fopenv.o\
	$(oDir)/outofmem.o\
	$(oDir)/rdcolor.o\
	$(oDir)/saccept.o\
	$(oDir)/sclose.o\
	$(oDir)/sgets.o\
	$(oDir)/sinit.o\
	$(oDir)/smaskwait.o\
	$(oDir)/smkskt.o\
	$(oDir)/sopen.o\
	$(oDir)/sopenv.o\
	$(oDir)/speek.o\
	$(oDir)/speeraddr.o\
	$(oDir)/speername.o\
	$(oDir)/sprintf.o\
	$(oDir)/sprt.o\
	$(oDir)/sprtskt.o\
	$(oDir)/sputs.o\
	$(oDir)/sread.o\
	$(oDir)/sreadbytes.o\
	$(oDir)/srmsrvr.o\
	$(oDir)/srmtrblk.o\
	$(oDir)/sscanf.o\
	$(oDir)/stest.o\
	$(oDir)/stimeoutwait.o\
	$(oDir)/stpblk.o\
	$(oDir)/stpnxt.o\
	$(oDir)/strnxtfmt.o\
	$(oDir)/svprintf.o\
	$(oDir)/swait.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libcsockets.a
ALLTGT	=	$(Bin)/libcsockets.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libcsockets.a: $(EXOBJS)
	rm -f $(Bin)/libcsockets.a
	ar cr $(Bin)/libcsockets.a $(EXOBJS)
	ranlib $(Bin)/libcsockets.a

$(oDir)/cprt.o: cprt.c xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/swrite.o: swrite.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/error.o: error.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/fopenv.o: fopenv.c xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/outofmem.o: outofmem.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/rdcolor.o: rdcolor.c xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/saccept.o: saccept.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sclose.o: sclose.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sgets.o: sgets.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sinit.o: sinit.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/smaskwait.o: smaskwait.c xtdio.h rdcolor.h setproto.h csockets.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/smkskt.o: smkskt.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sopen.o: sopen.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sopenv.o: sopenv.c xtdio.h rdcolor.h setproto.h csockets.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/speek.o: speek.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/speeraddr.o: speeraddr.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/speername.o: speername.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sprintf.o: sprintf.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sprt.o: sprt.c xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sprtskt.o: sprtskt.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sputs.o: sputs.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sread.o: sread.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sreadbytes.o: sreadbytes.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/srmsrvr.o: srmsrvr.c xtdio.h rdcolor.h setproto.h csockets.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/srmtrblk.o: srmtrblk.c
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sscanf.o: sscanf.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/stest.o: stest.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/stimeoutwait.o: stimeoutwait.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/stpblk.o: stpblk.c
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/stpnxt.o: stpnxt.c xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/strnxtfmt.o: strnxtfmt.c xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/svprintf.o: svprintf.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/swait.o: swait.c csockets.h xtdio.h rdcolor.h setproto.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
