#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (gcc).
# Generated 03:15:14 PM 17 Feb 2010
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc
LD  	=	gcc
WRES	=	windres
HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=	-L/usr/lib/X11 \
	-L/usr/X11R6/lib \
	-L../../clibrary

incDirs	=	-I/usr/include/X11 \
	-I/usr/X11R6/include \
	-I../../clibrary

LD_FLAGS =	-s
LIBS	=	-lm -lXxf86vm -lXcursor -lXpm -lXext -lX11 -lpthread -ldl -lm
C_FLAGS	=	-O

SRCS	=\
	xwinlite.c

EXOBJS	=\
	$(oDir)/xwinlite.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/libxwinlite.a
ALLTGT	=	$(Bin)/libxwinlite.a

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/libxwinlite.a: $(EXOBJS)
	rm -f $(Bin)/libxwinlite.a
	ar cr $(Bin)/libxwinlite.a $(EXOBJS)
	ranlib $(Bin)/libxwinlite.a

$(oDir)/xwinlite.o: xwinlite.c xwinlite.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
